config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "articles#index"
  resources :articles do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update] do
    member do
      get :followings
      get :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index
  resources :messages, only: :create
  resources :rooms, only: [:index, :create, :show]
end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :user
  has_many_attached :images
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  has_many :notifications, dependent: :destroy

  with_options presence: true do 
    validates :images
    validates :store_name
    validates :address
    validates :text
  end

  geocoded_by :address
  before_validation :geocode

  def create_notification_like!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and article_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        article_id: id,
        visited_id: user_id,
        action: 'like'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    temp_ids = Comment.select(:user_id).where(article_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end
  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      article_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # before_action :authenticate_user!, except: :index
  before_action :set_article, only: [:edit, :update, :show]
  before_action :move_root, only: [:edit, :update]
  def index
    @articles = Article.order('created_at DESC')
    @like = Like.new
  end
  
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @comment = Comment.new
    @comments = @article.comments.includes(:user)
    @like = Like.new
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to root_path
  end

  private
  def article_params
    params.require(:article).permit(:address, :store_name, :text, images: []).merge(user_id: current_user.id)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def move_root
    unless current_user.id == @article.user_id
      redirect_to root_path
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<%= render "shared/header" %>
<div class="contents_row">
  <div class="container">
    <h1>編集フォーム</h1>
    <div class="image-edit">
      <% @article.images.each do |image| %>
        <%= image_tag image, class: 'image-element' %>
      <% end %>
    </div>
    <%= form_with model: @article, class: "form_class", local: true do |f| %>
    
      <%= render 'shared/error_messages', model: f.object %>

      <%= f.file_field :images, name: 'article[images][]', id: 'article_image' %>
      <div id="image-list", class="image-list"></div>
      <%= f.label :store_name, "店舗名" %>
      <%= f.text_field :store_name, placeholder: "store name", class: "store_name", size: "35" %>
      <%= f.label :address, "住所" %>
      <%= f.text_area :address, placeholder: "address", class: "address", size: "35" %>
      <%= f.label :text, "投稿内容" %>
      <%= f.text_area :text, placeholder: "text", size: "35x8" %>
      <%= f.submit "送信", class: "submit" %>
    <% end %>
  </div>
</div>

app/views/articles/index.html.erb
<%= render "shared/header" %>
<h1>トップページ</h1>
<div class="contents_low">
  <% @articles.each do |article| %>
    <div class="more", id="more">
      <div class="articles">
        <% article.images.first(1).each do |image| %>
          <%= link_to image_tag(image, class: "images"), article_path(article.id)%>
        <% end %>
      </div>
      <hr>
      <div class="name">
          <div class="store-name>">店舗名_<%= article.store_name %></div>
          <div class="addoress">住所_<%= article.address %></div>
          <div class="text-form">投稿内容_</b><%= article.text %></div>
        </div>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<%= render "shared/header" %>
<div class="contents_row">
  <div class="container">
    <h1>投稿フォーム</h1>
    <% @article.images.each do |image| %>
      <%= image_tag image, class: 'images' %>
    <% end %>
    <%= form_with model: @article, class: "form_class", local: true do |f| %>

      <%= render 'shared/error_messages', model: f.object %>
      
      <%= f.file_field :images, name: 'article[images][]', id: 'article_image' %>
      <div id="image-list", class="image-list"></div>
      <%= f.label :store_name, "店舗名" %>
      <%= f.text_field :store_name, placeholder: "store name", class: "store_name", size: "35" %>
      <%= f.label :address, "住所" %>
      <%= f.text_area :address, placeholder: "address", class: "address", size: "35" %>
      <%= f.label :text, "投稿内容" %>
      <%= f.text_area :text, placeholder: "text", size: "35x8" %>
      <%= f.submit "送信", class: "submit" %>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<%= render "shared/header" %>
<h1>投稿詳細</h1>
<div class="contents_low">
  <div class="show-more">
    <div class="articles">
      <div class="main-image">
        <%= image_tag @article.images.first, class: "images" %>
      </div>
      <div class="grid-image">
        <% @article.images.each do |image| %>
          <%= image_tag image, class: "article-image" %>
        <% end %>
      </div>
    </div>
    <div class="name-area">
      <div class="store-name>">店舗名_<%= @article.store_name %></div>
      <div class="address-name">住所_<%= @article.address %></div>
      <div class="text-name">投稿内容_<%= @article.text %></div>
      <%= link_to @article.user.nickname, user_path(@article.user.id) %>
    </div>
    <% if user_signed_in? && current_user.id == @article.user_id %>
      <ul class="more-list">
        <li class="list">
          <%= link_to '編集', edit_article_path(@article.id), method: :get, class: "item-edit" %>
        </li>
        <li class="list">
          <%= link_to "削除", article_path(@article.id), method: :delete, class: "item-destroy" %>
        </li>
      </ul>
    <% end %>
  </div>
  <h2>いいねの数: <%= @article.likes.count %></h2>
  <% unless current_user.id == @article.user_id %>
    <% if current_user.already_liked?(@article) %>
      <%= button_to 'いいねを取り消す', article_like_path(@article), method: :delete %>
    <% else %>
      <%= button_to 'いいね', article_likes_path(@article) %>
    <% end %>
  <% end %>
  <h3>地図</h3>
  <div id='map'></div>
  <h4>コメントを送る</h4>
  <div class="container">
    <% if user_signed_in? %>
      <%= form_with model: [@article, @comment], class: :form_comments, local: true do |f| %>
        <%= f.text_area :text, placeholder: "コメントする" %>
        <%= f.submit "送信", class: "submit" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
  </div>
  <h5>＜コメント一覧＞</h5>
  <div class="comments">
    <% @comments.each do |comment| %>
      <div class="coment-list">
        <%= link_to comment.user.nickname, user_path(comment.user_id) %>
        <%= comment.text %>
      </div>
    <% end %>
  </div>

  <style type="text/css">
    #map {
      height: 400px;
      width: 100%;
    }
  </style>
  <script type="text/javascript">
    function initMap() {
      var test = {lat: <%= @article.latitude %>, lng: <%= @article.longitude %>};
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 15, 
        center: test
      });
      var transitLayer = new google.maps.TransitLayer();
      transitLayer.setMap(map);
      var contentString = '住所：<%= @article.address %>';
      var infowindow = new google.maps.InfoWindow({
        content: contentString
      });
      var marker = new google.maps.Marker({
        position:test,
        map: map,
        title: contentString
      });
      marker.addListener('click', function() {
        infowindow.open(map, marker);
      });
    }
  </script>
  <script async defer
    src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['MAP_API_KEY'] %>&callback=initMap">
  </script>
</div>