config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "articles#index"
  resources :articles do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update] do
    member do
      get :followings
      get :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index
  resources :messages, only: :create
  resources :rooms, only: [:index, :create, :show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  has_many :messages, dependent: :destroy
  has_many :entries
  has_many :rooms, through: :entries
  has_many :likes, dependent: :destroy
  has_many :like_articles, through: :likes , source: :article
  has_many :comments, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  
  with_options presence: true do
    validates :nickname
    validates :password, format: { with: /\A(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]{6,}\z/ }, on: :create
  end

  mount_uploader :image, ImageUploader

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_or_create_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def already_liked?(article)
    self.likes.exists?(article_id: article.id)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit]
  before_action :set_user, only: [:edit, :followings, :followers, :show]
  before_action :move_user, only: :edit
  def edit
  end

  def update
    user = User.find(params[:id])
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @articles = current_user.articles
    @relationship = current_user.relationships.find_by(follow_id: @user.id)  
    @set_relationship = current_user.relationships.new
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def followings
    @users = @user.followings.all
  end

  def followers
    @users = @user.followers.all
  end
  
  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:nickname, :email, :image)
  end

  def move_user
    unless current_user.id == @user.id
      redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render "shared/header" %>
<div class="contents_row">
  <div class="container">
    <h1>アカウント情報編集</h1>
    <h2>変更したい項目を入力してください</h2>
    <div class="user-edit">
      <%= form_with model: @user, url: user_path, method: :patch, class: "form-class", local: true do |f| %>

          <%= render 'shared/error_messages', model: f.object %>

        <div class="field">
          <%= f.label :"プロフィール画像"%><br />
          <%= f.file_field :image %>
        </div>
        <div class="field">
          <%= f.label :"ニックネーム"%><br />
          <%= f.text_field :nickname, autofocus: true, autocomplete: "nickname" %>
        </div>
        <div class="field">
          <%= f.label :"メールアドレス" %><br />
          <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
        </div>
        <div class="field">
          <%= f.label :"現在のパスワード" %> <i>(入力必須)</i><br />
          <%= f.password_field :current_password, autocomplete: "current-password" %>
        </div>
        <div class="field">
          <%= f.label :"変更後のパスワード" %> <i>(パスワード変更時入力)</i><br />
          <%= f.password_field :password, autocomplete: "new-password" %>
          <% if @minimum_password_length %>
            <br />
            <em><%= @minimum_password_length %> characters minimum</em>
          <% end %>
        </div>
        <div class="field">
          <%= f.label :"変更確認パスワード" %><i>(パスワード変更時入力)</i><br />
          <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
        </div>
        <div class="actions">
          <%= f.submit "更新", class: "submit" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<%= render "shared/header" %>
<h1>フォローされてます</h1>
<div class="follow-box">
  <% @users.each do |user| %>
    <div class="follow-list">
      <%= image_tag user.image.to_s, class: "icon" %>
      <%= link_to user.nickname, user_path(user.id) %>
    </div>
  <% end %>
</div>

app/views/users/followings.html.erb
<%= render "shared/header" %>
<h1>フォロー中</h1>
<div class="follow-box">
  <% @users.each do |user| %>
    <div class="follow-list">
      <%= image_tag user.image.to_s, class: "icon" %>
      <%= link_to user.nickname, user_path(user.id), class: "username" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<%= render "shared/header" %>
<div class="contents_low">
  <div class="user-pro"><%= @user.nickname %>さんのプロフィール</div>
  <%= image_tag @user.image.to_s, class: "image-icon" %>
  <% if user_signed_in? && current_user.id == @user.id %>
    <%= link_to 'アカウント情報編集', edit_user_path, method: :get, class: "lists" %>
  <% end %>
  <% unless @user.id == current_user.id %>
    <% if @isRoom == true %>
      <%= link_to "メッセージを送る", room_path(@roomId) %>
    <% else %>
      <%= form_with model: @room, local: true do |f| %>
        <%= fields_for @Entry do |r| %>
          <%= r.hidden_field :user_id, value: @user.id %>
        <% end %>
        <%= f.submit "チャットを始める" %>
      <% end %>
    <% end %>
  <% end %>
  <%= render "shared/follow", user: @user %>
  <% if @user.id == current_user.id %>
    <span>
      <%= link_to "フォロー: #{@user.followings.count}", followings_user_path(@user.id) %>
      <%= link_to "フォロワー: #{@user.followers.count}", followers_user_path(@user.id) %>
    </span>
  <% end %>
  <h1>投稿一覧</h1>
  <div class="contents_low" >
    <div class="article-list">
      <% @user.articles.each do |article| %>
        <%= link_to image_tag(article.images[0], class: "images"), article_path(article.id) %>
        <div class="name">
          <div class="store-name>">店舗名_<%= article.store_name %></div>
          <div class="addoress">住所_<%= article.address %></div>
          <div class="text-form">投稿内容_</b><%= article.text %></div>
          <div class="more-list">
            <% if user_signed_in? && current_user.id == article.user_id %>
              <%= link_to '編集', edit_article_path(article.id), method: :get, class: "lists" %>
              <%= link_to "削除", article_path(article.id), method: :delete, class: "lists" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <h2>いいねしている投稿</h2>
    <div class="article-list">
      <% @user.like_articles.each do |article| %>
        <%= link_to image_tag(article.images[0], class: "images"), article_path(article.id) %>
        <div class="name">
          <div class="store-name>">店舗名<%= article.store_name %></div>
          <div class="addoress">住所<%= article.address %></div>
          <div class="text-form">投稿内容</b><%= article.text %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>