config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "articles#index"
  resources :articles do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update] do
    member do
      get :followings
      get :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index
  resources :messages, only: :create
  resources :rooms, only: [:index, :create, :show]
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_follow.html.erb
<% unless current_user == @user %>
  <% if current_user.following?(@user) %>
    <%= form_with model: @relationship, url: relationship_path, method: :delete, local: true do |f| %>
      <%= hidden_field_tag :follow_id, @user.id %>
      <%= f.submit 'フォローを外す', class: "follow_btn" %>
    <% end %>
  <% else %>
    <%= form_with model: @set_relationship, url: relationships_path, local: true do |f| %>
      <%= hidden_field_tag :follow_id, @user.id %>
      <%= f.submit 'フォローする', class: "follow_btn" %>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_header.html.erb
<header class="header">
  <div class="wrapper_header">
    <div class='header_start'>
      <%= link_to 'original-app2', root_path, class: "original-icon" %>
    </div >
    <div class="header_end">
      <div class="nav">
        <ul class='nav-lists'>
          <% if user_signed_in? %>
            <li class="button">
              <%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname" %>
            </li>
            <li class="button">
              <%= link_to "投稿する", new_article_path, class: "post" %>
            </li>
            <li class="button">
              <%= link_to "通知", notifications_path, method: :get, class: "notification" %>
            </li>
            <li class="button">
              <%= link_to "トークルーム", rooms_path, method: :get, class: "room" %>
            <li>
            <li class="button">
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %>
            </li>
          <% else %>
            <li class="button">
              <%= link_to 'ログイン', new_user_session_path, class: "login" %>
            </li>
            <li class="button">
              <%= link_to '新規登録', new_user_registration_path, class: "sign-up" %>
            </li>
          <% end %>
        </ul>
      </div> 
    </div>
  </div>
</header>