config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "articles#index"
  resources :articles do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update] do
    member do
      get :followings
      get :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :notifications, only: :index
  resources :messages, only: :create
  resources :rooms, only: [:index, :create, :show]
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :users, through: :entries
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def index
    @rooms = current_user.rooms
    @currentEntries = current_user.entries
    myRoomIds = []
    @currentEntries.each do |entry|
      myRoomIds << entry.room.id
    end
    @anotherEntries = Entry.where(room_id: myRoomIds).where.not(user_id: current_user.id)
  end

  def create
    @room = Room.create
    @entry1 = Entry.create(user_id: current_user.id, room_id: @room.id )
    @entry2 = Entry.create(join_room_params)
    redirect_to room_path(@room.id)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
  private
  def join_room_params
    params.permit(:user_id, :room_id).merge(room_id: @room.id)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<%= render "shared/header" %>
<div class="talk-name">トークルーム</div>
<% @anotherEntries.each do |e| %>
  <div class="room-list">
    <%= link_to room_path(e.room.id) do %>
      <div class="room"><%= e.user.nickname %>さんとのルーム</div>
      <div class="room-text">
        <div class="text-box">
          <b>最終送信者</b>
          <%= Message.find_by(id: e.room.message_ids.last).user.nickname %>
          <b>メッセージ内容</b>
          <%= Message.find_by(id: e.room.message_ids.last).content %>
          <b>送信日時</b>
          <%= Message.find_by(id: e.room.message_ids.last).created_at.strftime("%Y年%m月%d日 %H時%M分") %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/rooms/show.html.erb
<%= render "shared/header" %>
<div class="header-message">
<%= render "shared/header" %>
  <span class="top-message">メッセージ</span>
  <div class="users-list">
    <b>トークに参加しているユーザー名</b>
    <% @entries.each do |r| %>
      <div class="user-name">
      <strong>
        <a class="rooms-user-link" href="/users/<%= r.user.id %>">
          <%= r.user.nickname %>さん
        </a>
      </strong>
      </div>
    <% end %>
  </div>
</div>
</div>
<hr>
<div class="chat">
  <% if @messages.present? %>
    <% @messages.each do |m| %>
      <div class="chat-box">
        <div class="chat-text">
          <% if m.user.id == current_user.id %>
            <div class="right-message">
              <%= m.created_at.strftime("%H:%M") %>
              <span class="content-box">
                <b><%= m.content %></b>
              </span>
            </div>
          <% else %>
            <div class="left-message">
              <span class="content-box">
                <b><%= m.content %></b>
              </span>
              <%= m.created_at.strftime("%H:%M") %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  <% else %>
    <P>メッセージはまだありません</p>
  <% end %>
</div>
<div class="form-message">
  <%= form_with model: @message, local: true do |f| %>
    <%= f.text_field :content, class: "message-content", placeholder: "メッセージを入力してください" %>
    <%= f.hidden_field :room_id, value:@room.id %>
    <%= f.submit"送信する", class: "message-submit" %>
  <% end %>
</div>